sudo: requires
services:
    - docker

before_install:
    - docker build -t tahifamed/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run tahifamed/react-test npm run test -- --coverage
after_success:
    - docker build -t tahifamed/multi-client ./client
    - docker build -t tahifamed/multi-nginx ./nginx
    - docker build -t tahifamed/multi-server ./server
    - docker build -t tahifamed/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tahifamed/multi-client
    - docker push tahifamed/multi-nginx
    - docker push tahifamed/multi-server
    - docker push tahifamed/multi-worker